//dats right punk! LXM
file_text_write_string(fileid,"Herocryption 1.4 (5 June 2009)"); file_text_writeln(fileid);
file_text_writeln(fileid);
file_text_write_string(fileid,"I'm the Hero Core savefile, bad to the B"); file_text_writeln(fileid);
file_text_write_string(fileid,"I won't take it easy if you mess with me"); file_text_writeln(fileid);
file_text_write_string(fileid,"Change a few letters, just for fun"); file_text_writeln(fileid);
file_text_write_string(fileid,"And all your saves'll be corrupted son"); file_text_writeln(fileid);
file_text_write_string(fileid,"So you'd better think twice before you try to cheat"); file_text_writeln(fileid);
file_text_write_string(fileid,"Don't cross me now 'less you can take the heat"); file_text_writeln(fileid);
file_text_writeln(fileid);
file_text_write_string(fileid,"It's the Hero Core savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Uh! Uh!)"); file_text_writeln(fileid);
file_text_write_string(fileid,"I'm the big bad savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Yo come on)"); file_text_writeln(fileid);
file_text_write_string(fileid,"It's the age ee savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Uh! Uh!)"); file_text_writeln(fileid);
file_text_write_string(fileid,"The double-hockeysticks savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Everybody come on)"); file_text_writeln(fileid);
file_text_writeln(fileid);
file_text_write_string(fileid,"My rhymes may be censored for the family good"); file_text_writeln(fileid);
file_text_write_string(fileid,"But when it comes to checksums, I know the hood"); file_text_writeln(fileid);
file_text_write_string(fileid,"I was raised by virii in the depths of DOS"); file_text_writeln(fileid);
file_text_write_string(fileid,"Where I learned the laws of the bits and the flops"); file_text_writeln(fileid);
file_text_write_string(fileid,"Edit my contents, and trust me I'll know"); file_text_writeln(fileid);
file_text_write_string(fileid,"Your saves will be forfeit, that's the point of my show"); file_text_writeln(fileid);
file_text_writeln(fileid);
file_text_write_string(fileid,"It's the Hero Core savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Uh! Uh!)"); file_text_writeln(fileid);
file_text_write_string(fileid,"I'm the big bad savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Yo come on)"); file_text_writeln(fileid);
file_text_write_string(fileid,"It's the HC savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Uh! Uh!)"); file_text_writeln(fileid);
file_text_write_string(fileid,"The bad attitude savefile"); file_text_writeln(fileid);
file_text_write_string(fileid,"(Everybody, yeeeah)"); file_text_writeln(fileid);
